spring.application.name=gerenciador-cardapio-spring

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciadorDeCardapioSpring
spring.datasource.username=postgres
spring.datasource.password=root

# criar/atualizar tabelas automaticamente pelo Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar os comandos SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true